"""Generate clinical readiness gate report from validation metrics artifacts.

This script consumes one or two `validation_metrics.json` files generated by
`scripts/validate_app_isic2018.py` and applies a screening-oriented gate
checklist.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
import json
import math
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class GateResult:
    """Single pass/fail gate outcome."""

    gate_id: str
    label: str
    value: float
    threshold: float
    operator: str
    passed: bool
    note: str = ""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build clinical readiness gate report.")
    parser.add_argument(
        "--val-metrics",
        type=Path,
        required=True,
        help="Path to validation_metrics.json for validation split.",
    )
    parser.add_argument(
        "--test-metrics",
        type=Path,
        default=None,
        help="Optional path to validation_metrics.json for held-out test split.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("outputs/reports"),
        help="Directory to write report files.",
    )
    parser.add_argument(
        "--report-name",
        type=str,
        default="clinical_readiness_report",
        help="Output filename stem (without extension).",
    )
    parser.add_argument(
        "--min-samples",
        type=int,
        default=150,
        help="Minimum samples required for split-level stability.",
    )
    parser.add_argument("--min-top1", type=float, default=0.70, help="Minimum top-1 accuracy.")
    parser.add_argument(
        "--min-balanced-accuracy",
        type=float,
        default=0.60,
        help="Minimum balanced accuracy.",
    )
    parser.add_argument("--min-macro-f1", type=float, default=0.55, help="Minimum macro-F1.")
    parser.add_argument(
        "--min-mel-triage-sensitivity",
        type=float,
        default=0.80,
        help="Minimum melanoma one-vs-rest sensitivity.",
    )
    parser.add_argument(
        "--min-mel-triage-specificity",
        type=float,
        default=0.70,
        help="Minimum melanoma one-vs-rest specificity.",
    )
    parser.add_argument(
        "--min-mel-npv",
        type=float,
        default=0.97,
        help="Minimum melanoma one-vs-rest negative predictive value.",
    )
    parser.add_argument(
        "--min-mel-class-recall",
        type=float,
        default=0.35,
        help="Minimum MEL per-class recall from multiclass confusion matrix.",
    )
    parser.add_argument(
        "--min-bcc-class-recall",
        type=float,
        default=0.60,
        help="Minimum BCC per-class recall from multiclass confusion matrix.",
    )
    parser.add_argument(
        "--min-akiec-class-recall",
        type=float,
        default=0.30,
        help="Minimum AKIEC per-class recall from multiclass confusion matrix.",
    )
    return parser.parse_args()


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Metrics file not found: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def _safe_float(value: Any) -> float:
    try:
        out = float(value)
    except Exception:
        return float("nan")
    if math.isnan(out) or math.isinf(out):
        return float("nan")
    return out


def _extract_class_recall(metrics: dict[str, Any], class_name: str) -> float:
    labels = metrics.get("labels", [])
    cm = metrics.get("confusion_matrix", [])
    if not isinstance(labels, list) or not isinstance(cm, list):
        return float("nan")
    labels_upper = [str(label).upper() for label in labels]
    target = class_name.upper()
    if target not in labels_upper:
        return float("nan")
    idx = labels_upper.index(target)
    if idx >= len(cm):
        return float("nan")
    row = cm[idx]
    if not isinstance(row, list):
        return float("nan")
    if idx >= len(row):
        return float("nan")
    total = sum(_safe_float(v) for v in row)
    if total <= 0:
        return float("nan")
    tp = _safe_float(row[idx])
    return tp / total


def _gate_min(
    gate_id: str,
    label: str,
    value: float,
    threshold: float,
    note: str = "",
) -> GateResult:
    passed = (not math.isnan(value)) and (value >= threshold)
    return GateResult(
        gate_id=gate_id,
        label=label,
        value=value,
        threshold=threshold,
        operator=">=",
        passed=passed,
        note=note,
    )


def _evaluate_split(metrics: dict[str, Any], args: argparse.Namespace) -> list[GateResult]:
    mel_bin = metrics.get("melanoma_one_vs_rest", {})
    total_samples = _safe_float(metrics.get("total_samples"))
    top1 = _safe_float(metrics.get("top1_accuracy"))
    bal = _safe_float(metrics.get("balanced_accuracy"))
    macro_f1 = _safe_float(metrics.get("macro_f1"))
    mel_sens = _safe_float(mel_bin.get("sensitivity"))
    mel_spec = _safe_float(mel_bin.get("specificity"))
    mel_npv = _safe_float(mel_bin.get("npv"))
    mel_recall = _extract_class_recall(metrics, "MEL")
    bcc_recall = _extract_class_recall(metrics, "BCC")
    akiec_recall = _extract_class_recall(metrics, "AKIEC")

    return [
        _gate_min(
            gate_id="sample_size",
            label="Sample size",
            value=total_samples,
            threshold=float(args.min_samples),
            note="Stability gate to avoid tiny-sample conclusions.",
        ),
        _gate_min("top1_accuracy", "Top-1 accuracy", top1, args.min_top1),
        _gate_min("balanced_accuracy", "Balanced accuracy", bal, args.min_balanced_accuracy),
        _gate_min("macro_f1", "Macro F1", macro_f1, args.min_macro_f1),
        _gate_min(
            "mel_triage_sensitivity",
            "MEL triage sensitivity",
            mel_sens,
            args.min_mel_triage_sensitivity,
        ),
        _gate_min(
            "mel_triage_specificity",
            "MEL triage specificity",
            mel_spec,
            args.min_mel_triage_specificity,
        ),
        _gate_min("mel_triage_npv", "MEL triage NPV", mel_npv, args.min_mel_npv),
        _gate_min("mel_class_recall", "MEL class recall", mel_recall, args.min_mel_class_recall),
        _gate_min("bcc_class_recall", "BCC class recall", bcc_recall, args.min_bcc_class_recall),
        _gate_min(
            "akiec_class_recall",
            "AKIEC class recall",
            akiec_recall,
            args.min_akiec_class_recall,
        ),
    ]


def _fmt_pct(value: float) -> str:
    if math.isnan(value):
        return "n/a"
    return f"{value * 100:.2f}%"


def _fmt_float(value: float) -> str:
    if math.isnan(value):
        return "n/a"
    return f"{value:.4f}"


def _split_payload(
    split_name: str,
    source_path: Path,
    metrics: dict[str, Any],
    gates: list[GateResult],
) -> dict[str, Any]:
    passed = sum(1 for gate in gates if gate.passed)
    total = len(gates)
    return {
        "split": split_name,
        "source_metrics_path": str(source_path),
        "preprocess": metrics.get("preprocess"),
        "total_samples": metrics.get("total_samples"),
        "gate_summary": {
            "passed": passed,
            "total": total,
            "all_passed": passed == total,
        },
        "gates": [
            {
                "id": gate.gate_id,
                "label": gate.label,
                "value": gate.value,
                "threshold": gate.threshold,
                "operator": gate.operator,
                "passed": gate.passed,
                "note": gate.note,
            }
            for gate in gates
        ],
    }


def _render_markdown(report: dict[str, Any]) -> str:
    lines: list[str] = []
    lines.append("# Clinical Readiness Gate Report")
    lines.append("")
    lines.append(f"- Generated at: `{report['generated_at_utc']}`")
    lines.append(f"- Overall verdict: **{report['overall_verdict']}**")
    lines.append("")
    lines.append("## Gate Profile")
    lines.append("")
    lines.append("`screening_v1`")
    lines.append("")

    for split in report["splits"]:
        lines.append(f"## Split: {split['split']}")
        lines.append("")
        lines.append(f"- Source: `{split['source_metrics_path']}`")
        lines.append(f"- Samples: `{split.get('total_samples', 'n/a')}`")
        gate_summary = split["gate_summary"]
        lines.append(
            f"- Gate pass count: `{gate_summary['passed']}/{gate_summary['total']}` "
            f"({'PASS' if gate_summary['all_passed'] else 'FAIL'})"
        )
        lines.append("")
        lines.append("| Gate | Value | Threshold | Result |")
        lines.append("|---|---:|---:|---:|")
        for gate in split["gates"]:
            gate_id = str(gate["id"])
            value = _safe_float(gate["value"])
            threshold = _safe_float(gate["threshold"])
            if gate_id == "sample_size":
                value_text = "n/a" if math.isnan(value) else f"{value:.0f}"
                threshold_text = "n/a" if math.isnan(threshold) else f"{threshold:.0f}"
            elif "f1" in gate_id:
                value_text = _fmt_float(value)
                threshold_text = _fmt_float(threshold)
            else:
                value_text = _fmt_pct(value)
                threshold_text = _fmt_pct(threshold)
            result_text = "PASS" if gate["passed"] else "FAIL"
            lines.append(f"| {gate['label']} | {value_text} | {threshold_text} | {result_text} |")
        lines.append("")

    failing = report.get("failing_gates", [])
    lines.append("## Failing Gates")
    lines.append("")
    if not failing:
        lines.append("- None")
    else:
        for row in failing:
            lines.append(
                f"- `{row['split']}`: `{row['gate_id']}` "
                f"(value={_fmt_float(_safe_float(row['value']))}, "
                f"threshold={_fmt_float(_safe_float(row['threshold']))})"
            )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    split_entries: list[tuple[str, Path, dict[str, Any], list[GateResult]]] = []
    val_metrics = _load_json(args.val_metrics)
    val_gates = _evaluate_split(val_metrics, args)
    split_entries.append(("val", args.val_metrics, val_metrics, val_gates))

    if args.test_metrics is not None:
        test_metrics = _load_json(args.test_metrics)
        test_gates = _evaluate_split(test_metrics, args)
        split_entries.append(("test", args.test_metrics, test_metrics, test_gates))

    split_payloads = [
        _split_payload(split_name, source_path, metrics, gates)
        for split_name, source_path, metrics, gates in split_entries
    ]

    failing_gates: list[dict[str, Any]] = []
    for split_name, _, _, gates in split_entries:
        for gate in gates:
            if gate.passed:
                continue
            failing_gates.append(
                {
                    "split": split_name,
                    "gate_id": gate.gate_id,
                    "value": gate.value,
                    "threshold": gate.threshold,
                }
            )

    overall_pass = len(failing_gates) == 0
    report_payload = {
        "generated_at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "overall_verdict": "PASS" if overall_pass else "FAIL",
        "splits": split_payloads,
        "failing_gates": failing_gates,
        "profile": "screening_v1",
    }

    json_path = args.out_dir / f"{args.report_name}.json"
    md_path = args.out_dir / f"{args.report_name}.md"
    json_path.write_text(json.dumps(report_payload, indent=2), encoding="utf-8")
    md_path.write_text(_render_markdown(report_payload), encoding="utf-8")

    print(f"Report JSON: {json_path}")
    print(f"Report MD: {md_path}")
    print(f"Overall verdict: {report_payload['overall_verdict']}")
    if failing_gates:
        print(f"Failing gates: {len(failing_gates)}")


if __name__ == "__main__":
    main()
